name: Archived Examples CI
on:
    workflow_dispatch:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test-examples:
        name: Test Examples
        runs-on: ubuntu-latest
        env:
            ganache-image: trufflesuite/ganache-cli:v6.12.2

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: '1.23'
            - run: go version

            - uses: actions/cache@v4
              with:
                path: |
                    ~/.cache/go-build
                    ~/go/pkg/mod
                key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                restore-keys: |
                    ${{ runner.os }}-go-

            - name: Pull ganache-cli image
              run: docker pull ${{ env.ganache-image }}

            - name: Simple Client
              working-directory: simple-client
              env:
                MNEMONIC: pistol kiwi shrug future ozone ostrich match remove crucial oblige cream critic
              run: |
                docker run --rm --name ganache --detach --publish 8545:8545 ${{ env.ganache-image }} -b 5 -a 2 -m "$MNEMONIC"
                sleep 5
                go run .
                docker stop ganache
            
            - name: Collateralized Channels
              working-directory: collateralized-channels
              env:
                GANACHE_CMD: "docker run --name ganache --rm --publish 8545:8545 ${{ env.ganache-image }}"
              run: | 
                docker stop ganache || true # Cleanup any previous instance

                go test -v -timeout 60s .
                docker stop ganache || true

        